version: "3"
services: 
  samba:
    image: tetra61/samba:1.0
    container_name: smb_server
    restart: always
    ports: 
      - 139:139
      - 445:445

    environment:
      USERNAME: hoge
      PASSWD: fuga

    volumes:
      # client permissions
      # private USERNAME:USERNAME 755
      # public root:root 777
      - /mnt/disk0/samba/hoge:/home/hoge
      - /mnt/disk0/samba/public:/home/public 
